name: docker-build-push

on:
  workflow_dispatch:
    inputs:
      dockerfile_path:
        description: 'Dockerfile 路径'
        required: true
        default: './Dockerfile'
      image_name:
        description: '构建的镜像名称'
        required: true
        default: 'inkeyp/ubuntu'

jobs:
  build:
    # 使用最新的 Ubuntu 环境
    runs-on: ubuntu-latest

    env:
      # 默认为 Docker Hub，如果使用其他 Docker 注册表，可以修改
      REGISTRY: 'docker.io'
      # 镜像名称通过输入的参数动态设置
      IMAGE_NAME: ${{ github.event.inputs.image_name }}

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 构建 Docker 镜像
      - name: Build Docker image
        run: docker build -f ${{ github.event.inputs.dockerfile_path }} . --tag ${{ env.IMAGE_NAME }}:latest

      # 登录到 Docker Hub（或其他 Docker 注册表）
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 提取 Docker 元数据（标签和标签）
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

      # 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ github.event.inputs.dockerfile_path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
